services:
  app:
    build:
      context: .
      dockerfile: ./nodejs/Dockerfile
    tty: true
    volumes:
      - ./:/app
    environment:
      - WATCHPACK_POLLING=true
    ports:
      - "3000:3000"
    networks:
      - app_net

networks:
  app_net:
