version: "3"
services:
  nodejs:
    container_name: nodejs
    build:
      context: ./nodejs
      dockerfile: Dockerfile
      args:
        - USER_ID=502 # ホスト側のユーザーIDに変更してください
        - GROUP_ID=20 # ホストのグループIDに変更してください
        - APP_NAME=asset_watch
    tty: true
    volumes:
      - ./:/app
    environment:
      - WATCHPACK_POLLING=true
    ports:
      - "3000:3000"
    networks:
      - app_net
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/24
