services:
  nodejs:
    container_name: nodejs
    build:
      context: ./nodejs
      dockerfile: Dockerfile
      args:
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
        - APP_NAME=asset_watch
    tty: true
    volumes:
      - ./:/app
    environment:
      - WATCHPACK_POLLING=true
    ports:
      - "3000:3000"
    networks:
      - app_net

networks:
  app_net:
